### ISSUE TITLE
Add "Get recommendations by category" function into RESTful API

### ISSUE THREAD

**Issue by ameryisafreeelf** [NYUDevOps-Fall18-Recommendations/recommendations#11]
**As a** ... customer
**I need** ... recommendations under specific categories  
**So that** ... I can have recommendations that best fit my preferences

**Assumptions:** 
* ... recommendations are tagged with categories

**Acceptance Criteria:**
```
Given ... our database with recommendations records
When ... we query based on categories
Then ... we get recommendations that only belong to that category
```

**Comment by yc2945** [comment]
I don't think we've implemented this. 
Correct me if I were wrong.
