### ISSUE TITLE
Create a features folder

### ISSUE THREAD

**Issue by rajBandhakavi** [NYUDevOps-Fall18-Recommendations/recommendations#112]
**As a Developer** ...  
**I need Features folder** ...  
**So that I can add my features file to perform BDD** ...  

**Assumptions:** 
* ...

**Acceptance Criteria:**
```
Given that I dont have a features folder  ...
When I add the features folder and move .features file to that folder ...
Then I have my .features file in the features folder...
```

**Comment by ameryisafreeelf** [comment]
@rajBandhakavi Sorry for not making it clear, but i did this under "create BDD environment" without making an explicit issue for it. I have the pull request active now.

**Comment by rajBandhakavi** [comment]
Alright I was wondering why the .features file outside features folder so I created this issue.

**Comment by ameryisafreeelf** [comment]
Thanks, sorry for confusion.
